name: Deployment
on:
  push:
    branches:
      - main

jobs:
  Deploy-Prod-Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: yarn install --frozen-lockfile
      - run: yarn build    
        env:
          CI: false
      - name: Copy folder content recursively to vps
        uses: appleboy/scp-action@master
        with:
          # source: "/home/runner/work/german-learning/german-learning/app/build"
          source: "./app/build/*"
          target: ${{ secrets.DEPLOY_PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # local: build
          # remote: ${{ secrets.DEPLOY_PATH }}
      - run: echo "🍏 This job's status is ${{ job.status }}."