name: Deployment
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'app'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: yarn install --frozen-lockfile
      - run: yarn build    
        env:
          CI: false
      - name: Copy folder content recursively to vps
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: ${{ secrets.DEPLOY_PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_SECRET_KEY }}
      - run: echo "🍏 This job's status is ${{ job.status }}."